# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "809765a4dafdd5c70bfacfdb543f3ace"
name = "two"
handle = "two-17"
application_url = "https://repeat-leasing-downloaded-meanwhile.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gelax.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://repeat-leasing-downloaded-meanwhile.trycloudflare.com/auth/callback",
  "https://repeat-leasing-downloaded-meanwhile.trycloudflare.com/auth/shopify/callback",
  "https://repeat-leasing-downloaded-meanwhile.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
